### PR TITLE
Add link to third Manjaro SSL expiry

### PR DESCRIPTION
**Pull request by Strykar**
Might be easier to create a counter to track this gift that keeps on giving?

### CODE REVIEW

**Comment by EmeraldSnorlax** [comment]
this says a lot about society

**Comment by Strykar** [comment]
@EmeraldSnorlax Unsure what you mean exactly. Thanks for merging.

**Comment by EmeraldSnorlax** [comment]
> Might be easier to create a counter to track this gift that keeps on giving?

watch https://github.com/EmeraldSnorlax/manjarno/tree/stopwatch :trollface:

**Comment by Strykar** [comment]
LoL

**Pull request merged**
